# Generated by Django 5.2.6 on 2025-10-06 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0003_variants_varianttype_productvariant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
