# Generated by Django 5.2.6 on 2025-10-07 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0004_remove_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ProductVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product")),
                ("is_default", models.BooleanField(default=False)),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Ekartapp.productvariant",
                    ),
                ),
            ],
        ),
    ]
