# Generated by Django 5.2.6 on 2025-10-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0005_productvariant_is_default_productvariantimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
