# Generated by Django 5.2.6 on 2025-10-08 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0006_usermodel_status_alter_useraddress_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="primary_variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_variant_type",
                to="Ekartapp.varianttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="secondary_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secondary_variant_type",
                to="Ekartapp.varianttype",
            ),
        ),
    ]
