# Generated by Django 5.2.6 on 2025-10-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0011_carouselimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order Placed", "Order Placed"),
                    ("READY", "Shipment Ready"),
                    ("DELIVERED", "Order Delivered"),
                ],
                default="Order Placed",
                max_length=20,
            ),
        ),
    ]
