# Generated by Django 5.2.6 on 2025-10-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0012_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order Placed", "Order Placed"),
                    ("Shipment Ready", "Shipment Ready"),
                    ("Order Delivered", "Order Delivered"),
                ],
                default="Order Placed",
                max_length=20,
            ),
        ),
    ]
