# Generated by Django 5.2.6 on 2025-10-13 10:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0013_alter_order_address_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_name", models.CharField(blank=True, max_length=250)),
                ("discount_percentage", models.PositiveIntegerField(default=0)),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.datetime(
                            2025,
                            10,
                            13,
                            10,
                            20,
                            35,
                            582253,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer",
                        to="Ekartapp.productvariant",
                    ),
                ),
            ],
        ),
    ]
