# Generated by Django 5.2.6 on 2025-10-13 12:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0014_productoffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoffer",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 10, 13, 12, 10, 33, 647460, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
