# Generated by Django 5.2.6 on 2025-10-13 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0015_alter_productoffer_start_date_emailotp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="email",
        ),
        migrations.AlterField(
            model_name="productoffer",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 10, 13, 12, 32, 56, 672287, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
