# Generated by Django 5.2.6 on 2025-10-14 05:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0016_remove_usermodel_email_alter_productoffer_start_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductOffer",
        ),
    ]
