# Generated by Django 5.2.6 on 2025-10-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0017_delete_productoffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="home_name",
            field=models.CharField(default="manzil", max_length=100),
        ),
    ]
