# Generated by Django 5.2.6 on 2025-10-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0018_useraddress_home_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupons",
            name="discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
