# Generated by Django 5.2.6 on 2025-10-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0019_alter_coupons_discount_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="variants",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="varianttype",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
