# Generated by Django 5.2.6 on 2025-10-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0020_variants_status_varianttype_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variants",
            name="variant_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="Ekartapp.varianttype",
            ),
        ),
    ]
