# Generated by Django 5.2.6 on 2025-10-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0021_alter_variants_variant_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
