# Generated by Django 5.2.6 on 2025-10-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0022_productvariant_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
