# Generated by Django 5.2.6 on 2025-10-18 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Ekartapp", "0023_orderitem_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariant",
            old_name="status",
            new_name="variant_status",
        ),
    ]
