# Generated by Django 5.1.6 on 2025-02-22 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vaccine_app", "0004_alter_complaints_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaccine_Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vaccine_app.vaccineshedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment",
                        to="vaccine_app.user",
                    ),
                ),
                (
                    "vaccine_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vaccine_app.vaccine",
                    ),
                ),
            ],
        ),
    ]
